# Generated by Django 2.2.1 on 2019-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag_id',
        ),
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
