# Generated by Django 2.2.1 on 2019-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_tag', '0002_auto_20190516_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
